// Module included in the following assemblies:
//
// * openshift_images/using_images/using-images-source-to-image.adoc

[id="images-using-images-s2i-java_{context}"]
= Java overview

{product-title} provides a source-to-image (S2I) builder image for building Java applications. This builder image takes your application source or binary artifacts, builds the source using Maven if a source was provided, and assembles the artifacts with any required dependencies to create a new, ready-to-run image containing your Java application. This resulting image can be run on {product-title}.

The builder image is intended for use with link:https://maven.apache.org[Maven]-based Java standalone projects that are run with main class.

[id="images-s2i-java-versions_{context}"]
== Versions

The current version of the Java S2I builder image supports OpenJDK 1.8, Jolokia 1.3.5, and Maven 3.3.9-2.8.

[discrete]
== Additional resources

* Find additional information and examples in the link:https://access.redhat.com/documentation/en-us/red_hat_jboss_middleware_for_openshift/3/html-single/red_hat_java_s2i_for_openshift/[Red Hat JBoss Middleware] documentation.
