// Module included in the following assemblies:
// * installing/installing_openstack/uninstalling-openstack-user.adoc
:playbook-version: 4.7

[id="installation-osp-downloading-playbooks_{context}"]
= Downloading the removal playbooks

Download Ansible playbooks that you can use to uninstall {product-title} from your own {rh-openstack-first} infrastructure.

.Prerequisites

* The curl command-line tool is available on your machine.
* You have the `inventory.yaml` file that you used to install the cluster. 
+
[NOTE]
====
If you do not have the `inventory.yaml` file, you can download it by entering this command in a command line:

[source,terminal,subs=attributes+]
----
curl -O https://raw.githubusercontent.com/openshift/installer/release-{playbook-version}/upi/openstack/inventory.yaml
----

Modify the values in the file to match your cluster configuration before proceeding.
====

.Procedure

. To download the playbooks to your working directory, run the following script from a command line:
+
[source,terminal,subs=attributes+]
----
$ xargs -n 1 curl -O <<< '                                
        https://raw.githubusercontent.com/openshift/installer/release-{playbook-version}/upi/openstack/common.yaml                                     
        https://raw.githubusercontent.com/openshift/installer/release-{playbook-version}/upi/openstack/down-bootstrap.yaml                             
        https://raw.githubusercontent.com/openshift/installer/release-{playbook-version}/upi/openstack/down-compute-nodes.yaml                         
        https://raw.githubusercontent.com/openshift/installer/release-{playbook-version}/upi/openstack/down-control-plane.yaml                         
        https://raw.githubusercontent.com/openshift/installer/release-{playbook-version}/upi/openstack/down-load-balancers.yaml                        
        https://raw.githubusercontent.com/openshift/installer/release-{playbook-version}/upi/openstack/down-network.yaml                               
        https://raw.githubusercontent.com/openshift/installer/release-{playbook-version}/upi/openstack/down-security-groups.yaml                       
        https://raw.githubusercontent.com/openshift/installer/release-{playbook-version}/upi/openstack/down-containers.yaml'
----

The playbooks are downloaded to your machine.