// Module included in the following assemblies:
//
// * installing/installing_openstack/installing-openstack-user.adoc
// * installing/installing_openstack/installing-openstack-user-kuryr.adoc

[id="installation-osp-creating-compute-machines_{context}"]
= Creating compute machines on {rh-openstack}

After standing up the control plane, create compute machines.

.Prerequisites
* The `inventory.yaml`, `common.yaml`, and `compute-nodes.yaml` Ansible playbooks are in a common directory.
** If you need these files, download them in "Downloading the installation playbooks."
* The `metadata.yaml` file that the installation program created is in the same directory as the Ansible playbooks.
* The control plane is active.

.Procedure

. On a command line, change the working directory to the location of the playbooks.

. On a command line, run the playbook:
+
[source,terminal]
----
$ ansible-playbook -i inventory.yaml compute-nodes.yaml
----

.Next steps

* Approve the machines' certificate signing requests
