// Module included in the following assemblies:
//
// * installing/installing_openstack/installing-openstack-user.adoc
// * installing/installing_openstack/installing-openstack-user-kuryr.adoc

[id="installation-osp-configuring-sr-iov_{context}"]
= Creating compute machines that use SR-IOV hardware

If your {rh-openstack-first} deployment supports link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.1/html-single/network_functions_virtualization_planning_and_configuration_guide/index#assembly_sriov_parameters[single root I/O virtualization (SR-IOV)], you can provision an SR-IOV network that compute machines run on.


.Prerequisites

* Your cluster supports SR-IOV.
+
[NOTE]
====
If you are unsure about what your cluster supports, review the {product-title} SR-IOV hardware networks documentation.
====

* You installed the SR-IOV Network Operator on your cluster.

.Procedure

. On a command line, create a {rh-openstack} network:
+
[source,terminal]
----
$ openstack network create radio --provider-physical-network radio --provider-network-type vlan --provider-segment 120
----
+
[NOTE]
====
In these example commands, the network is named `radio`.
====

. Create a subnet that uses your CIDR range:
+
[source,terminal]
----
$ openstack subnet create radio --network radio --subnet-range <your_CIDR_range> --dhcp
----

. Create a port that allows machines to connect to your cluster and each other:
+
[source,terminal]
----
$ openstack port os_port_worker_0 --network <infrastructure_ID>-network --security-group <infrastructure_ID>-worker --fixed-ip subnet=<infrastructure_ID>-nodes,ip-address=<fixed_IP_address> --allowed-address ip-address=<infrastructure_ID>-ingress-port
----

. Create a port for SR-IOV traffic:
+
[source,terminal]
----
$ openstack port create radio_port --vnic-type direct --network radio --fixed-ip subnet=radio,ip-address=<fixed_IP_address> --tag=radio --disable-port-security
----

. Create an {rh-openstack} server instance that uses the two ports you created as NICs:
+
[source,terminal]
----
$ openstack server create --image <infrastructure_ID>-rhcos --flavor ocp --user-data <ocp project>/build-artifacts/worker.ign --nic port-id=<os_port_worker_0 ID> --nic port-id=<radio_port_ID> --config-drive true worker-<worker_ID>.<cluster_name>.<cluster_domain>
----

Your cluster can now run compute machines on an SR-IOV network.