// Module included in the following assemblies:
//
// * installing/installing_openstack/installing-openstack-user.adoc

[id="installation-osp-creating-control-plane_{context}"]
= Creating the control plane machines on {rh-openstack}

Create three control plane machines by using the Ignition config files that you generated.

.Prerequisites

* The infrastructure ID from the installation program's metadata file is set as an environment variable (`$INFRA_ID`).
* The `inventory.yaml`, `common.yaml`, and `control-plane.yaml` Ansible playbooks are in a common directory.
** If you need these files, copy them from "Downloading the installation playbooks."
* The three Ignition files created in "Creating control plane Ignition config files."

.Procedure

. On a command line, change the working directory to the location of the playbooks.

. If the control plane Ignition config files aren't already in your working directory, copy them into it.

. On a command line, run the `control-plane.yaml` playbook:
+
[source,terminal]
----
$ ansible-playbook -i inventory.yaml control-plane.yaml
----

. Run the following command to monitor the bootstrapping process:
+
[source,terminal]
----
$ openshift-install wait-for bootstrap-complete
----
+
You will see messages that confirm that the control plane machines are running and have joined the cluster:
+
[source,terminal]
----
INFO API v1.14.6+f9b5405 up
INFO Waiting up to 30m0s for bootstrapping to complete...
...
INFO It is now safe to remove the bootstrap resources
----
