// Module included in the following assemblies:
//
// * installing/installing_osp/uninstalling-cluster-osp.adoc

[id="installation-uninstall-infra_{context}"]
= Removing a cluster from {rh-openstack} that uses your own infrastructure

You can remove an {product-title} cluster on {rh-openstack-first} that uses your own infrastructure. To complete the removal process quickly, download and run several Ansible playbooks.

.Prerequisites

* Python 3 is installed on your machine.
* You downloaded the modules in "Downloading playbook dependencies."
* You downloaded the playbooks in "Downloading installation playbooks."

.Procedure

. On a command line, run the playbooks that you downloaded:
+
[source,terminal]
----
$ ansible-playbook -i inventory.yaml  \
	down-bootstrap.yaml      \
	down-control-plane.yaml  \
	down-compute-nodes.yaml  \
	down-load-balancers.yaml \
	down-network.yaml        \
	down-security-groups.yaml
----

. Remove any DNS record changes you made for the {product-title} installation.

{product-title} is removed from your infrastructure.
