// Module included in the following assemblies:
//
// * nodes/nodes-cluster-enabling-features.adoc

[id="nodes-cluster-enabling-features-cli_{context}"]
= Enabling feature sets using the CLI

You can use the {product-title} CLI to enable feature sets for all nodes in the cluster.

.Procedure

To enable feature sets:

. Edit the Feature Gate custom resource (CR), named `cluster`, in the `openshift-config` project:
+
[source,terminal]
----
$ oc edit featuregate cluster -n openshift-config
----
+
.Sample Feature Gate custom resource
[source,yaml]
----
apiVersion: config.openshift.io/v1
kind: FeatureGate
metadata:
  name: cluster
....

spec:
  featureSet: LatencySensitive <1>
----
+
--
<1> Add the feature sets that you want to enable in a comma-separated list:
* `IPv6DualStackNoUpgrade` to enable the dual-stack networking mode.
* `LatencySensitive` to enable the Topology Manager.
* `TechPreviewNoUpgrade` to enable specific Technology Preview features.
--
+
[NOTE]
====
Enabling the `TechPreviewNoUpgrade` or `IPv6DualStackNoUpgrade` feature sets cannot be undone and prevents upgrades.
====
