// Module included in the following assemblies:
//
// * nodes/nodes-cluster-enabling-features.adoc

[id="nodes-cluster-features-about_{context}"]
= Understanding feature gates

You can use the Feature Gate custom resource (CR) to enable specific feature sets throughout your cluster. A feature set is a specific collection of {product-title} features that are not enabled by default. 

For example, the `TechPreviewNoUpgrade` feature set allows you to enable a subset of the current Technology Preview features on test clusters, where you can fully test them, while leaving the features disabled on production clusters.

You can activate any of the following feature sets by using the Feature Gate (CR):

[options="header"]
|===
| FeatureSet| Description

|`IPv6DualStackNoUpgrade`
|Enables the dual-stack networking mode in your cluster. Dual-stack networking supports the use of IPv4 and IPv6 simultaneously. Turning on this feature set is not supported, cannot be undone, and prevents upgrades. 

|`LatencySensitive`
|Enables the Topology Manager in your cluster. Upgrades are enabled with this feature.

|`TechPreviewNoUpgrade`
a|Turns on Technology Preview features that are not part of the normal supported platform. Turning on this feature set cannot be undone and prevents upgrades. 

The following Technology Preview features are enabled by this feature set:

* link:https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/#certificate-rotation[RotateKubeletServerCertificate]. Enable the rotation of the server TLS certificate on the kubelet.
* SupportPodPidsLimit. Enables limiting PIDs in Pods.

|===

//// 
Do not document per Derek Carr: https://github.com/openshift/api/pull/370#issuecomment-510632939
|`CustomNoUpgrade` ^[2]^
|Allows the enabling or disabling of any feature. Turning on this feature set on is not supported, cannot be undone, and prevents upgrades. 

[.small]
--
1. 
2. If you use the `CustomNoUpgrade` feature set to disable a feature that appears in the web console, you might see that feature, but
no objects are listed. For example, if you disable builds, you can see the *Builds* tab in the web console, but there are no builds present. If you attempt to use commands associated with a disabled feature, such as `oc start-build`, {product-title} displays an error.

[NOTE]
====
If you disable a feature that any application in the cluster relies on, the application might not
function properly, depending upon the feature disabled and how the application uses that feature.
====
////
