// Module included in the following assemblies:
//
// * networking/ovn_kubernetes_network_provider/deploying-egress-router-ovn-redirection.adoc

ifeval::["{context}" == "deploying-egress-router-cni-redirection"]
:redirect:
:router-type: redirect
endif::[]

[id="nw-egress-router-network-attachment_{context}"]
= Network attachment definition for an egress router in {router-type} mode

Before a pod can act as an egress router, you must specify the network interface configuration as a `NetworkAttachmentDefinition` object.
The object specifies information such as the IP address to attach to the egress router pod, network destinations, and a network gateway.
As the pod for the egress router starts, Multus uses the network attachment definition to add a network interface with the specified properties to the pod.

.Example network attachment definition
[source,yaml]
----
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: egress-router-redirect  <.>
spec:
  config: '{
    "cniVersion": "0.4.0",
    "type": "egress-router",
    "name": "egress-router",
    "ip": {
      "addresses": [
        "192.168.12.99"  <.>
        ],
      "destinations": [
        "192.168.12.91"  <.>
      ],
      "gateway": "192.168.12.1"  <.>
      }
    }'
----
<.> The name of the network attachment definition is used later in the specification for the egress router pod.

<.> The `addresses` key specifies the reserved source IP address to use with the additional network interface.
+
Optional: You can include the subnet length, such as `192.168.12.99/24`, so that a route to the local subnet is set. If you do not specify a subnet length, then the egress router can access only the host specified with the `gateway` key and no other hosts on the subnet.

<.> The `destinations` key specifies one or more IP addresses that the egress router sends packets to. The network address translation (NAT) tables for the egress router pod are configured so that connections to the cluster IP address of the pod are redirected to the same port on a destination IP address. Using this example, connections to the pod are redirected to `192.168.12.91`, with a source IP address of `192.168.12.99`.

<.> The `gateway` key specifies the IP address for the network gateway.

// clear temporary attributes
:!router-type:
ifdef::redirect[]
:!redirect:
endif::[]
