// Module included in the following assemblies:
// TODO
// * networking/TBD
// For thinking and reviewing, adding to networking/load-balancing-openstack.adoc

[id="nw-osp-configuring-external-load-balancer_{context}"]
= Configuring an external load balancer

You can configure a {product-title} cluster on {rh-openstack-first} to use an external load balancer.

// Maybe an About mod in support

.Prerequisites

* On your load balancer, ports 6443, 443, and 80 must be available to any users of your system.
* On your load balancer, port 22623, which is used to serve ignition start-up configurations to nodes, is not exposed outside of the cluster.

.Procedure

// TODO: network formatting... style guide.
. On your {rh-openstack} deployment, add floating IP addresses to all master nodes. For example:
+
[source,terminal]
----
$ openstack floating ip create --port master-port-0 <public_network>
----
+
[source,terminal]
----
$ openstack floating ip create --port master-port-1 <public_network>
----
+
[source,terminal]
----
$ openstack floating ip create --port master-port-2 <public_network>
----

. Find the floating IP addresses that are associated with your nodes:
+
[source,terminal]
----
$ openstack server list
----

. Use the floating IP addresses for the nodes to enable access to the cluster from your load balancer on ports 6443, 443, and 80.
+
As an example, see this HAProxy configuration for port 6443:
+
.A section of a sample HAProxy configuration
[source,text]
----
...
listen my-cluster-api-6443
    bind 0.0.0.0:6443
    mode tcp
    balance roundrobin
    server my-cluster-master-2 192.0.2.2:6443 check
    server my-cluster-master-0 192.0.2.0:6443 check
    server my-cluster-master-1 192.0.2.1:6443 check
...
----

. Enable network access to the master nodes from the load balancer network over ports 6443, 443, and 80:
+
[source,terminal]
----
$ openstack security group rule create master --remote-ip <load_balancer_cidr> --ingress --protocol tcp --dst-port 6443
----
+
[source,terminal]
----
$ openstack security group rule create master --remote-ip <load_balancer_cidr> --ingress --protocol tcp --dst-port 443
----
+
[source,terminal]
----
$ openstack security group rule create master --remote-ip <load_balancer_cidr> --ingress --protocol tcp --dst-port 80
----
+
[NOTE]
====
You can specify specific IP addresses by using `/32` in the load balancer CIDR argument.
====

. Add a record to your DNS server for the load balancer. For example:
+
[source,dns]
----
<load_balancer_ip_address> api.<cluster_name>.<base_domain>
----

. From a command line, use `curl` to verify that the external load balancer and DNS configuration are operational. For example:
+
[source,terminal]
----
curl https://<loadbalancer_ip_address>:6443/version --insecure
----
+
If the configuration is correct, you receive a JSON object in response:
+
[source,json]
----
{
  "major": "1",
  "minor": "11+",
  "gitVersion": "v1.11.0+ad103ed",
  "gitCommit": "ad103ed",
  "gitTreeState": "clean",
  "buildDate": "2019-01-09T06:44:10Z",
  "goVersion": "go1.10.3",
  "compiler": "gc",
  "platform": "linux/amd64"
}
----