// Module included in the following assemblies:
//
// web_console/odc-about-web-terminal.adoc

[id="odc-using-web-terminal_{context}"]
= Using the web terminal

After the *Web Terminal* Operator is installed, you can use the web terminal as follows:

. Click the command line terminal icon (image:odc-wto-icon[title="wto icon"]) on the upper right of the console to launch the web terminal. An automatically logged in web terminal instance that uses your credentials is displayed at the bottom of the screen.
. In the *Command line terminal* pane, select the project, from the *Project* drop-down list, where the `DevWorkspace` CR must be created. By default, the current project is selected.
+
[NOTE]
====
* The `DevWorkspace` CR is created only if it does not already exist.
* The `openshift-terminal` project is the default project used for cluster administrators. They do not have the option to choose another project.
====
+
. Click *Start* to initialize the web terminal using the selected project.

After the web terminal is initialized, you can use the pre-installed CLI tools like `oc`, `kubectl`, `odo`, `kn`, `tkn`, `helm`, `kubens`, and `kubectx` in the web terminal.
