// Module included in the following assemblies:
//
// * operators/operator_sdk/osdk-golang-tutorial.adoc

[id="osdk-bundling-deploying-using-olm_{context}"]
= Bundling and deploying your Operator using OLM

Operator Lifecycle Manager (OLM) helps you to install, update, and generally manage the lifecycle of all of the Operators and their associated services on a Kubernetes cluster. OLM is installed by default on {product-title} and runs as an Kubernetes extension, allowing you to use the {product-title} web console and `oc` for all the lifecycle management functions without any additional tools.

This example walks through getting an Operator ready for OLM using the Bundle Format, the default packaging format for Operator SDK and OLM.

.Prerequisites

- Operator SDK CLI installed on a development workstation
- OpenShift CLI (`oc`) v{product-version}+ installed
- Operator Lifecycle Manager (OLM) installed on a Kubernetes-based cluster (v1.16.0 or above if using `apiextensions.k8s.io/v1` CRDs, for example {product-title} {product-version})
- Logged into the cluster with `oc` using an account with `cluster-admin` permissions
- Memcached Operator built using Operator SDK.

.Procedure

. You can check the status of OLM on your cluster by using the following Operator SDK command:
+
[source,terminal]
----
$ operator-sdk olm status \
    --olm-namespace=openshift-operator-lifecycle-manager
----

. Bundle manifests for an Operator describe how to display, create, and manage an application, in this case Memcached. Create bundle manifests by running the following command, which invokes several commands, including the Operator SDK `generate bundle` and `bundle validate` subcommands:
+
[source,terminal]
----
$ make bundle
----
+
This creates the following in your Operator project:
+
--
* a bundle manifests directory `bundle/manifests` containing a `ClusterServiceVersion` (CSV) object
* a bundle metadata directory `bundle/metadata`
* all CRDs in `config/crd`
* a Dockerfile `bundle.Dockerfile`
--
+
These files are then statically validated by `operator-sdk bundle validate` automatically to ensure the on-disk bundle representation is correct.

. OLM consumes Operator bundles using an _index image_, which are composed of one or more _bundle images_. Build and push a `memcached-operator` bundle image by running the following commands:
+
[source,terminal]
----
$ make bundle-build BUNDLE_IMG=<registry>/<user>/memcached-operator-bundle:<tag>
----
+
[source,terminal]
----
$ docker push <registry>/<user>/memcached-operator-bundle:<tag>
----

. You can now use the following command to run your Operator on your cluster using OLM:
+
[source,terminal]
----
$ operator-sdk run bundle <registry>/<user>/memcached-operator-bundle:<tag>
----
+
This command automates the following:
+
--
* Create an index image with your bundle image injected.
* Create a catalog source that points to your new index image, which enables OperatorHub to discover your Operator.
* Deploy your Operator to your cluster by creating an Operator group, subscription, install plan, and all other required objects, including RBAC.
--
