// Module included in the following assemblies:
//
// * operators/operator_sdk/osdk-golang-tutorial.adoc

[id="osdk-golang-run-in-cluster_{context}"]
= Running as a deployment inside the cluster

You can run your Operator project as a deployment inside of your cluster.

.Procedure

. *Build and push the image.*

.. Before building the Operator image, ensure the generated Dockerfile references the base image you want. You can change the default "runner" image `gcr.io/distroless/static:nonroot` by replacing its tag with another, for example `alpine:latest`, and removing the `USER: nonroot:nonroot` directive.

.. To build and push the Operator image, use the following `make` commands. Modify the `IMG` argument in the example below to reference a repository that you have access to. You can obtain an account for storing containers at repository sites such as Quay.io, which this example uses.

... Build the image:
+
[source,terminal]
----
$ export USERNAME=<quay_username>
----
+
[source,terminal]
----
$ make docker-build IMG=quay.io/$USERNAME/memcached-operator:v0.0.1
----

... Push the image to a repository:
+
[source,terminal]
----
$ make docker-push IMG=quay.io/$USERNAME/memcached-operator:v0.0.1
----
+
[NOTE]
====
The name and tag of the image, for example `IMG=<registry>/<user>/<image_name>:<tag>`, in both the commands can also be set in your Makefile. Modify the line which has `IMG ?= controller:latest` to set your default image name.
====

. *Deploy the Operator.*

.. By default, a new namespace is created with name `<project_name>-system`, for example `memcached-operator-system`, and is used for the deployment.
+
Run the following command to deploy the Operator. This also installs the RBAC manifests from `config/rbac`:
+
[source,terminal]
----
$ make deploy IMG=quay.io/$USERNAME/memcached-operator:v0.0.1
----
+
[NOTE]
====
If you have enabled webhooks in your deployments, you must have cert-manager already installed in the cluster or the `make deploy` command will fail when creating the cert-manager resources.
====

.. Verify that the `memcached-operator` is up and running:
+
[source,terminal]
----
$ oc get deployment -n memcached-operator-system
----
+
.Example output
[source,terminal]
----
NAME                                    READY   UP-TO-DATE   AVAILABLE   AGE
memcached-operator-controller-manager   1/1     1            1           8m
----
