// Module included in the following assemblies:
//
// * virt/virtual_machines/virtual_disks/virt-creating-and-using-boot-sources.adoc

[id="virt-creating-a-vm-from-a-boot-source_{context}"]
= Creating a new virtual machine from an added boot source template

After you add a boot source to a template, you create a new virtual machine from the template.

.Procedure

. In the {product-title} web console, click *Workloads > Virtualization* in the sidebar menu. The *Virtualization* page displays.
. Create a virtual machine or virtual machine template from a boot source.
.. Select *Create Virtual Machine > New with Wizard*. The *Create Virtual Machine* wizard displays.
.. On the *General* wizard page, select an OS from the *Operating System* list that displays the *(Source available)* label next to the OS and version name. The *(Source available)* label indicates boot sources are available for this OS.
.. Ensure that the *Clone available operating system source* check box is selected.
.. Click the *Review and Confirm* button.
.. On the *Review and confirm your settings* wizard page, review information about your virtual machine and change them, if required.
.. Click *Create Virtual Machine* to create your virtual machine. The *Successfully created virtual machine* page displays with links to *See virtual machine details* or *Go to list*, to display the list of virtual machines and virtual machine templates.
